; [defaults]
; interpreter_python=/usr/bin/python3
[local]
localhost ansible_connection=local

[prod]
worker1 ansible_host=34.177.81.36 ansible_user=pisethkhon888

[dev]
worker2 ansible_host=34.87.80.214 ansible_user=pisethkhon888


[all:children]
local
prod
dev
; ansible -i inventory.ini localhost -m ping