- name: Run Nginx Container 
  hosts: worker2
  vars: 
    docker_image: "nginx:latest"

  # ansible 
    # built -in command , atp ,...#rbos dea mean srab
    # community
  tasks: 
    # just like running docker command 
    # docker run -dp ...

    - name: Run Nginx Container 
      community.docker.docker_container: # mudule
        name: nginx_test_container 
        image: "{{ docker_image }}"
        state: started # absent for remove
        restart_policy: always # when server reboot , it will bring container up again ! 
        published_ports: 
          - "3000:80"