[all:vars]
ansible_user=pisethkhon888
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master02 ansible_host=34.177.86.242
master03 ansible_host=35.240.237.226


[workers]
worker01 ansible_host=34.92.61.65
worker02 ansible_host=34.150.62.8
