[all:vars]
ansible_user=pisethkhon888
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master02 ansible_host=136.110.63.26
master03 ansible_host=136.110.45.164


[workers]
worker01 ansible_host=34.142.251.212
worker02 ansible_host=34.34.216.46
