; [defaults]
; interpreter_python=/usr/bin/python3
[local]
localhost ansible_connection=local

; [prod]
; worker1 ansible_host=34.124.170.246 ansible_user=pisethkhon888

; [dev]
; worker2 ansible_host=34.87.119.241 ansible_user=pisethkhon888

[prod]
worker1 ansible_host=35.240.221.51 

[dev]
worker2 ansible_host=34.87.175.134 

[all:children]
local
prod
dev
; ansible -i inventory.ini localhost -m ping